Repository kyma-project/addons, pull requests merged in 2018-10, with the labels that each got.

#7 Update documentation
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
  .github/stale.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE.md
  README.md
  bundles/README.md
  bundles/showcase/README.md
  bundles/stable/README.md
  scripts/convert.sh
Labels: area/documentation, enhancement

#9 Add validator steps for bundles
  .travis.yml
  bundles/showcase/order-ec-0.0.1/chart/order-ec/.helmignore
  bundles/showcase/order-ec-0.0.1/chart/order-ec/Chart.yaml
  bundles/showcase/order-ec-0.0.1/chart/order-ec/templates/_helpers.tpl
  bundles/showcase/order-ec-0.0.1/chart/order-ec/templates/function.yaml
  bundles/showcase/order-ec-0.0.1/chart/order-ec/values.yaml
  bundles/showcase/order-service-0.0.1/chart/order-service/.helmignore
  bundles/showcase/order-service-0.0.1/chart/order-service/Chart.yaml
  bundles/showcase/order-service-0.0.1/chart/order-service/templates/_helpers.tpl
  bundles/showcase/order-service-0.0.1/chart/order-service/templates/order-service.yaml
  bundles/showcase/order-service-0.0.1/chart/order-service/values.yaml
  scripts/checker.sh
  scripts/convert.sh
  scripts/targz
Labels: area/service-catalog, enhancement

#8 Add how to started with bundles documentation
  README.md
  docs/README.md
  docs/get-started.md
Labels: enhancement

#14 Copy template for security issues
  .github/ISSUE_TEMPLATE/security-vulnerability.md
Labels: area/documentation, area/security, enhancement

#21 Add showcase label for lambda-rc bundle
  bundles/lambda-rc-0.0.1/meta.yaml
Labels: area/service-catalog, enhancement
