Repository kyma-project/addons, pull requests merged in 2019-05, with the labels that each got.

#85 Fix dead links
  bundles/azure-service-broker-0.0.1/README.md
  bundles/gcp-service-broker-0.0.2/README.md
Labels: area/documentation, bug

#87 Update testing bundle with RegExp
  bundles/testing-0.0.1/plans/full/create-instance-schema.json
Labels: area/console, enhancement

#92 Move redis to index-testing
  bundles/index-testing.yaml
  bundles/index.yaml
Labels: area/service-catalog, enhancement

#91 Add docs to the testing bundle
  bundles/testing-0.0.1/docs/assets/hodor.png
  bundles/testing-0.0.1/docs/configuration.md
  bundles/testing-0.0.1/docs/meta.yaml
  bundles/testing-0.0.1/docs/overview.md
  bundles/testing-0.0.1/docs/plans-details.md
  bundles/testing-0.0.1/docs/streetlights.yml
  bundles/testing-0.0.1/docs/swagger.json
  bundles/testing-0.0.1/docs/tutorial.md
Labels: area/core-and-supporting, area/documentation
