Repository kyma-project/addons, pull requests merged in 2019-12, with the labels that each got.

#124 Change DocsTopic to AssetGroup
  addons/aws-service-broker-0.0.1/README.md
Labels: area/documentation

#126 Fix a dead link
  docs/getting-started.md
Labels: area/documentation

#127 Fix a dead link
  docs/getting-started.md
Labels: area/documentation, bug

#128 Rename DocsTopics to AssetGroups in broker charts
  addons/aws-service-broker-0.0.1/chart/aws-service-broker/templates/docu/docs.yaml
  addons/aws-service-broker-0.0.1/chart/aws-service-broker/templates/docu/job.yaml
  addons/aws-service-broker-0.0.1/chart/aws-service-broker/templates/docu/role.yaml
  addons/azure-service-broker-0.0.1/chart/azure-service-broker/templates/docu/docs.yaml
  addons/azure-service-broker-0.0.1/chart/azure-service-broker/templates/docu/job.yaml
  addons/azure-service-broker-0.0.1/chart/azure-service-broker/templates/docu/role.yaml
  addons/gcp-service-broker-0.1.0/chart/gcp-service-broker/templates/docu/docs.yaml
  addons/gcp-service-broker-0.1.0/chart/gcp-service-broker/templates/docu/job.yaml
  addons/gcp-service-broker-0.1.0/chart/gcp-service-broker/templates/docu/role.yaml
Labels: area/core-and-supporting
