Repository kyma-project/addons, pull requests merged in 2019-03, with the labels that each got.

#70 Fix the links in the bundles repo docs
  docs/getting-started.md
Labels: area/documentation, bug

#71 Change the codeowners file
  CODEOWNERS
Labels: area/documentation

#72 Correct the dead link
  docs/getting-started.md
Labels: area/documentation

#73 Introduce istio to bundles
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/charts/redis/templates/_helpers.tpl
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/charts/redis/templates/metrics-deployment.yaml
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/charts/redis/templates/redis-master-statefulset.yaml
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/charts/redis/templates/redis-slave-deployment.yaml
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/templates/deployment.yaml
  bundles/redis-0.0.3/chart/redis/templates/deployment.yaml
  bundles/testing-0.0.1/chart/testing/templates/deploy.yaml
Labels: area/service-catalog
