Repository kyma-project/addons, pull requests merged in 2019-07, with the labels that each got.

#97 Remove GCP Broker
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/values.yaml
  bundles/gcp-service-broker-0.0.2/README.md
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/.helmignore
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/Chart.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/_helpers.tpl
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/docs.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/docu/job.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/docu/role-binding.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/docu/role.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/docu/sa.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/pod.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/post-install-job.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/pre-delete-job.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/role-binding.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/role.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/templates/sa.yaml
  bundles/gcp-service-broker-0.0.2/chart/gcp-service-broker/values.yaml
  bundles/gcp-service-broker-0.0.2/docs/bigquery/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/bigquery/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/broker/assets/gcp-broker-deprovisioning.svg
  bundles/gcp-service-broker-0.0.2/docs/broker/assets/gcp-broker-key-management.svg
  bundles/gcp-service-broker-0.0.2/docs/broker/assets/gcp-broker-provisioning.svg
  bundles/gcp-service-broker-0.0.2/docs/broker/overview.md
  bundles/gcp-service-broker-0.0.2/docs/broker/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-bigtable/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-bigtable/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-iam-service-account/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-iam-service-account/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-pubsub/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-pubsub/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-spanner/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-spanner/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-sql-mysql/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/cloud-sql-mysql/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/google-cloud-storage/docs/overview.md
  bundles/gcp-service-broker-0.0.2/docs/google-cloud-storage/docs/plans-details.md
  bundles/gcp-service-broker-0.0.2/docs/meta.yaml
  bundles/gcp-service-broker-0.0.2/meta.yaml
  bundles/gcp-service-broker-0.0.2/plans/default/create-instance-schema.json
  bundles/gcp-service-broker-0.0.2/plans/default/meta.yaml
  bundles/gcp-service-broker-0.0.2/plans/default/values.yaml
  bundles/index.yaml
Labels: area/service-catalog

#101 Update metadata in the testing bundles docs
  bundles/testing-0.0.1/docs/configuration.md
  bundles/testing-0.0.1/docs/plans-details.md
  bundles/testing-0.0.1/docs/tutorial-deployment.md
  bundles/testing-0.0.1/docs/tutorial-publish.md
Labels: area/documentation

#102 Fix a dead link
  docs/getting-started.md
Labels: area/documentation

#105 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community
