Repository kyma-project/addons, pull requests merged in 2019-02, with the labels that each got.

#59 Change core-helm-broker to helm-broker
  docs/getting-started.md
Labels: area/documentation

#61 Fix broken links
  docs/getting-started.md
Labels: area/documentation, bug

#63 Fix links that failed in the nightly governance job
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/charts/redis/README.md
  bundles/redis-0.0.3/chart/redis/README.md
Labels: area/documentation

#64 Update broken links
  README.md
  docs/getting-started.md
Labels: area/documentation

#68 Fix broken links
  docs/getting-started.md
Labels: area/documentation

#67 Remove pre-delete-job from AzureBroker
  bundles/azure-service-broker-0.0.1/chart/azure-service-broker/templates/pre-delete-job.yaml
Labels: area/service-catalog
